# Practica 6 - Numpy

In [1]:
import numpy as np

In [12]:
#1. Resolver con numpy. Dado:
lista_de_listas=[[-44,12], [12.0,51], [1300, -5.0]]
a = np.array(lista_de_listas)
print(f"Matriz original: \n{a}")
# Restarle 5 a la fila 2 de la matriz
resta = a[1,:] - 5
print(f"restarle 5 a la fila 2: \n{resta}")
# Multiplicar por 2 toda la matriz
mult = a*2
print(f"Multiplicar por 2 la matriz: \n{mult}")
# Dividir por -5 las dos primeras filas de la matriz
div = a[:2,:] / -5
print(f"Dividir por -5 las dos primeras filas: \n{div}")
#Imprimir la última fila de la matriz
ultima_fila = a[2,:]
print(f"Última fila: {ultima_fila}")

Matriz original: 
[[ -44.   12.]
 [  12.   51.]
 [1300.   -5.]]
restarle 5 a la fila 2: 
[ 7. 46.]
Multiplicar por 2 la matriz: 
[[ -88.   24.]
 [  24.  102.]
 [2600.  -10.]]
Dividir por -5 las dos primeras filas: 
[[  8.8  -2.4]
 [ -2.4 -10.2]]
Última fila: [1300.   -5.]
