# Practica 6 - Numpy

In [1]:
import numpy as np

## 1) Resolver con numpy. Dado:

In [20]:
lista_de_listas=[[-44,12], [12.0,51], [1300, -5.0]]
a = np.array(lista_de_listas)
print(f"Matriz original: \n{a}")
# Restarle 5 a la fila 2 de la matriz
resta = a[1,:] - 5
print(f"1) Restarle 5 a la fila 2: \n{resta}")
# Multiplicar por 2 toda la matriz
mult = a*2
print(f"2) Multiplicar por 2 la matriz: \n{mult}")
# Dividir por -5 las dos primeras filas de la matriz
div = a[:2,:] / -5
print(f"3) Dividir por -5 las dos primeras filas: \n{div}")
#Imprimir la última fila de la matriz
ultima_fila = a[2,:]
print(f"4) Última fila: \n{ultima_fila}")

Matriz original: 
[[ -44.   12.]
 [  12.   51.]
 [1300.   -5.]]
1) Restarle 5 a la fila 2: 
[ 7. 46.]
2) Multiplicar por 2 la matriz: 
[[ -88.   24.]
 [  24.  102.]
 [2600.  -10.]]
3) Dividir por -5 las dos primeras filas: 
[[  8.8  -2.4]
 [ -2.4 -10.2]]
4) Última fila: 
[1300.   -5.]


## 2) Resolver con numpy. Calcular la suma de los elementos de a (ejercicio anterior) utilizando dos fors anidados

In [29]:
# Calcular la suma de los elementos de a utilizando np.sum
suma = np.sum(a)
print(f"Suma de los elementos: {suma}")
# Calcular el promedio de los elementos de las primeras dos filas utilizando np.mean
#IMPLEMENTAR
promedio = np.mean(a[:2,:])
print(f"Promedio de los elementos de las primeras dos filas: {promedio}")

Suma de los elementos: 1326.0
Promedio de los elementos de las primeras dos filas: 7.75


## 3) Generar una matriz de 7 por 9. Las primeras 3 columnas de la matriz tienen que tener el valor 0. La cuarta columna debe tener el valor 0.5, excepto por el último valor de esa columna, que tiene que ser 0.7. Las otras tres columnas deben tener el valor 1. Luego imprimir la matriz. Imprimir también el promedio de la última fila.

In [33]:
matriz = np.array(
    [(0,0,0,0,0,0,0,0,0),
    (0,0,0,0,0,0,0,0,0),
    (0,0,0,0,0,0,0,0,0),
    (0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.7),
    (1,1,1,1,1,1,1,1,1),
    (1,1,1,1,1,1,1,1,1),
    (1,1,1,1,1,1,1,1,1)])

print(f'Matriz: \n{matriz}')

Matriz: 
[[0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.7]
 [1.  1.  1.  1.  1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1.  1.  1.  1.  1. ]]


## 4) Crear una matriz aleatoria de 5 por 5 con valores entre 0 y 1

In [38]:
matriz_aleatoria=np.random.rand(5,5)
print(matriz_aleatoria)

[[0.03004008 0.1247743  0.21687336 0.09528238 0.69483607]
 [0.17303191 0.24595789 0.33111699 0.59702048 0.88275272]
 [0.40131224 0.49595778 0.76990198 0.59888329 0.40623123]
 [0.30230934 0.01591366 0.58593818 0.96684969 0.38462085]
 [0.14528429 0.35953053 0.55055534 0.15151736 0.46866678]]
